[package]
name = "RustTrade"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
uuid = { version = "1", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.8"